// src/apis/sales_orders.js
import { apiClient } from '../utils/apiClient.js';
import { getCompanyName, getUserUUID } from '../apis/auth.js';

const API_BASE_URL = import.meta.env.VITE_API_LOGIN_BASE_URL;

function buildApiUrl(endpoint) {
  const companyName = getCompanyName();
  if (!companyName) throw new Error('Company name not found in localStorage. Please log in.');
  if (!API_BASE_URL) throw new Error('VITE_API_LOGIN_BASE_URL is not defined.');
  return `${API_BASE_URL}${companyName}/${endpoint}`;
}

const CREDIT_LIMIT_REGEX = /Credit limit exceeded\. Available credit:\s*(-?\d+(?:\.\d+)?),\s*required:\s*(-?\d+(?:\.\d+)?)/i;

const formatCurrencyAr = (value) => {
  const number = Number(value);
  if (Number.isNaN(number)) return value;
  return `${number.toLocaleString('ar-EG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ج.م`;
};

const translateCreditLimitMessage = (message) => {
  const match = CREDIT_LIMIT_REGEX.exec(message || '');
  if (!match) {
    return 'تم تجاوز حد الائتمان للعميل. يرجى تحصيل دفعة أو تعديل حد الائتمان قبل إصدار الفاتورة.';
  }

  const available = formatCurrencyAr(match[1]);
  const required = formatCurrencyAr(match[2]);

  return `الرصيد المتاح حالياً للعميل هو ${available} بينما يتطلب هذا الطلب ${required}. يرجى تحصيل دفعة أو زيادة حد الائتمان قبل المتابعة.`;
};

const mapCreditLimitErrorMessage = (message) => {
  if (!message) return message;
  if (/credit limit exceeded/i.test(message)) {
    return translateCreditLimitMessage(message);
  }
  return message;
};

/**
 * Add a new sales order
 */
export const addSalesOrder = async (orderData) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  const url = buildApiUrl("sales_orders/add.php");
  const formData = new FormData();
  
  // Add user UUID
  formData.append('users_uuid', users_uuid);
  
  // Add order data (order_number is auto-generated by database)
  formData.append('sales_orders_client_id', orderData.sales_orders_client_id);
  formData.append('sales_orders_order_date', orderData.sales_orders_order_date);
  formData.append('sales_orders_status', orderData.sales_orders_status);
  
  // Add delivery status if provided
  if (orderData.sales_orders_delivery_status) {
    formData.append('sales_orders_delivery_status', orderData.sales_orders_delivery_status);
  }
  
  if (orderData.sales_orders_notes) {
    formData.append('sales_orders_notes', orderData.sales_orders_notes);
  }
  if (orderData.sales_orders_warehouse_id) {
    formData.append('sales_orders_warehouse_id', orderData.sales_orders_warehouse_id);
  }
  if (orderData.sales_orders_representative_id) {
    formData.append('sales_orders_representative_id', orderData.sales_orders_representative_id);
  }
  if (orderData.sales_orders_expected_delivery_date) {
    formData.append('sales_orders_expected_delivery_date', orderData.sales_orders_expected_delivery_date);
  }
  if (orderData.sales_orders_subtotal) {
    formData.append('sales_orders_subtotal', orderData.sales_orders_subtotal);
  }
  if (orderData.sales_orders_discount_amount) {
    formData.append('sales_orders_discount_amount', orderData.sales_orders_discount_amount);
  }
  if (orderData.sales_orders_tax_amount) {
    formData.append('sales_orders_tax_amount', orderData.sales_orders_tax_amount);
  }
  if (orderData.sales_orders_total_amount) {
    formData.append('sales_orders_total_amount', orderData.sales_orders_total_amount);
  }
  if (orderData.items && orderData.items.length > 0) {
    formData.append('items', JSON.stringify(orderData.items));
  }

  const response = await apiClient.postFormData(url, formData);
  if (response.status === "success") {
    return response;
  }

  const message = mapCreditLimitErrorMessage(response.message) || 'Failed to add sales order';
  throw new Error(message);
};

/**
 * Update an existing sales order
 */
export const updateSalesOrder = async (orderData) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  const url = buildApiUrl("sales_orders/update.php");
  const formData = new FormData();
  
  // Add user UUID and ID
  formData.append('users_uuid', users_uuid);
  formData.append('sales_orders_id', orderData.sales_orders_id);
  
  // Add order data with correct field names matching backend expectations
  formData.append('sales_orders_client_id', orderData.sales_orders_client_id);
  formData.append('sales_orders_order_date', orderData.sales_orders_order_date);
  formData.append('sales_orders_status', orderData.sales_orders_status);
  
  // Add delivery status if provided
  if (orderData.sales_orders_delivery_status) {
    formData.append('sales_orders_delivery_status', orderData.sales_orders_delivery_status);
  }
  
  if (orderData.sales_orders_notes) {
    formData.append('sales_orders_notes', orderData.sales_orders_notes);
  }
  if (orderData.sales_orders_warehouse_id) {
    formData.append('sales_orders_warehouse_id', orderData.sales_orders_warehouse_id);
  }
  if (orderData.sales_orders_representative_id) {
    formData.append('sales_orders_representative_id', orderData.sales_orders_representative_id);
  }
  if (orderData.sales_orders_expected_delivery_date) {
    formData.append('sales_orders_expected_delivery_date', orderData.sales_orders_expected_delivery_date);
  }
  if (orderData.sales_orders_subtotal) {
    formData.append('sales_orders_subtotal', orderData.sales_orders_subtotal);
  }
  if (orderData.sales_orders_discount_amount) {
    formData.append('sales_orders_discount_amount', orderData.sales_orders_discount_amount);
  }
  if (orderData.sales_orders_tax_amount) {
    formData.append('sales_orders_tax_amount', orderData.sales_orders_tax_amount);
  }
  if (orderData.sales_orders_total_amount) {
    formData.append('sales_orders_total_amount', orderData.sales_orders_total_amount);
  }
  if (orderData.items && orderData.items.length > 0) {
    formData.append('items', JSON.stringify(orderData.items));
  }

  const response = await apiClient.postFormData(url, formData);
  if (response.status === "success") {
    return response;
  }

  const message = mapCreditLimitErrorMessage(response.message) || 'Failed to update sales order';
  throw new Error(message);
};

/**
 * Delete a sales order
 */
export const deleteSalesOrder = async (id) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  const url = buildApiUrl("sales_orders/delete.php");
  const formData = new FormData();
  
  formData.append('users_uuid', users_uuid);
  formData.append('sales_orders_id', id);

  const response = await apiClient.postFormData(url, formData);
  if (response.status === "success") {
    return response;
  } else {
    throw new Error(response.message || 'Failed to delete sales order');
  }
};

/**
 * Get all sales orders
 */
export const getAllSalesOrders = async (options = {}) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  let url = buildApiUrl("sales_orders/get.php");
  // Append query parameters for paging/filters
  const params = new URLSearchParams();
  params.set('users_uuid', users_uuid);
  if (options.page != null) params.set('page', String(options.page));
  if (options.limit != null) params.set('limit', String(options.limit));
  if (options.offset != null) params.set('offset', String(options.offset));
  if (options.status) params.set('status', String(options.status));
  if (options.client_id) params.set('client_id', String(options.client_id));
  if (options.delivery_status) params.set('delivery_status', String(options.delivery_status));
  if (options.representative_id) params.set('representative_id', String(options.representative_id));
  if (options.warehouse_id) params.set('warehouse_id', String(options.warehouse_id));
  if (options.date_from) params.set('date_from', String(options.date_from));
  if (options.date_to) params.set('date_to', String(options.date_to));
  if (options.search) params.set('search', String(options.search));
  url += `?${params.toString()}`;

  const response = await apiClient.get(url);
  
  if (response.status === "success" && response.data) {
    return response.data;
  } else {
    throw new Error(response.message || 'Failed to fetch sales orders');
  }
};

/**
 * Get sales order details
 */
export const getSalesOrderDetails = async (id) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  let url = buildApiUrl("sales_orders/get.php");
  // Append users_uuid and id as query parameters for GET requests
  url += `?users_uuid=${users_uuid}&id=${id}`;

  const response = await apiClient.get(url);
  if (response.status === "success" && response.data) {
    return response.data;
  } else {
    throw new Error(response.message || 'Failed to fetch sales order details');
  }
};

/**
 * Update sales order delivery status
 */
export const updateSalesOrderDeliveryStatus = async (salesOrderId, deliveryStatus, notes = '') => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  const url = buildApiUrl("sales_orders/update_delivery_status.php");
  const formData = new FormData();
  
  formData.append('users_uuid', users_uuid);
  formData.append('sales_orders_id', salesOrderId);
  formData.append('sales_orders_delivery_status', deliveryStatus);
  if (notes) {
    formData.append('notes', notes);
  }

  const response = await apiClient.postFormData(url, formData);
  if (response.status === "success") {
    return response;
  } else {
    throw new Error(response.message || 'Failed to update delivery status');
  }
};

/**
 * Get sales orders by client ID
 */
export const getSalesOrdersByClient = async (clientId, lastN = null) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  let url = buildApiUrl("sales_orders/get.php");
  // Append users_uuid and client_id as query parameters for GET requests
  url += `?users_uuid=${users_uuid}&client_id=${clientId}`;
  
  // Add last_n parameter if provided to limit the number of orders
  if (lastN && !isNaN(lastN)) {
    url += `&last_n=${lastN}`;
  }

  const response = await apiClient.get(url);
  if (response.status === "success" && response.data) {
    // Unwrap to get the array of orders regardless of shape
    if (Array.isArray(response.data)) return response.data;
    if (response.data && Array.isArray(response.data.data)) return response.data.data;
    return [];
  } else {
    throw new Error(response.message || 'Failed to fetch client sales orders');
  }
};

/**
 * Get sales orders that need delivery (server-side filtering)
 * Filters for orders with status 'Confirmed' or 'Invoiced', delivery status not 'Delivered',
 * and have items with remaining quantity > 0
 */
export const getDeliverableSalesOrders = async (options = {}) => {
  const users_uuid = getUserUUID();
  if (!users_uuid) throw new Error('User UUID is required. Please log in.');

  let url = buildApiUrl("sales_orders/get_deliverable.php");
  // Append query parameters
  const params = new URLSearchParams();
  params.set('users_uuid', users_uuid);
  
  // Add any additional filtering options
  if (options.page != null) params.set('page', String(options.page));
  if (options.limit != null) params.set('limit', String(options.limit));
  if (options.client_id) params.set('client_id', String(options.client_id));
  if (options.warehouse_id) params.set('warehouse_id', String(options.warehouse_id));
  if (options.date_from) params.set('date_from', String(options.date_from));
  if (options.date_to) params.set('date_to', String(options.date_to));
  if (options.search) params.set('search', String(options.search));
  
  url += `?${params.toString()}`;

  const response = await apiClient.get(url);
  
  if (response.status === "success" && response.data) {
    return response.data;
  } else {
    throw new Error(response.message || 'Failed to fetch deliverable sales orders');
  }
};
